import { useState, type ReactNode } from "react";
import type { LayerDetail, LayerName, PerGeneResult, RankedCellLine } from "../types/scoring";
import { formatScore } from "../lib/formatScore";
import { stateLabel } from "../lib/layerStateLabel";

interface ResultFlowchartDiagramProps {
  line: RankedCellLine;
  partitionBucket: string;
}

// Fixed hand-authored layout, following DataSchemaPage.tsx's foreignObject-per-node technique.
// Row x-positions are generated by summing each node's own width + a fixed gap -- still a fixed,
// hand-designed reading order (not a force-directed graph library), just computed rather than
// hand-typed per box, since two lanes of ~13 boxes each is too easy to mistype by hand.
const GAP_X = 36;
const LANE1_Y = 24;
const LANE2_Y = 400;
const TIER_Y = 660;

interface NodeSpec {
  id: string;
  width: number;
  height: number;
}

function layoutRow(specs: NodeSpec[], y: number): Record<string, { x: number; y: number; w: number; h: number }> {
  const out: Record<string, { x: number; y: number; w: number; h: number }> = {};
  let x = 24;
  for (const spec of specs) {
    out[spec.id] = { x, y, w: spec.width, h: spec.height };
    x += spec.width + GAP_X;
  }
  return out;
}

const LANE1_SPECS: NodeSpec[] = [
  { id: "spine", width: 170, height: 100 },
  { id: "identity-bridge", width: 210, height: 130 },
  { id: "dup-rna", width: 210, height: 130 },
  { id: "layer-states", width: 320, height: 280 },
  { id: "protein-impute", width: 210, height: 130 },
  { id: "transforms", width: 320, height: 280 },
  { id: "coverage-states", width: 230, height: 130 },
];

const LANE2_SPECS: NodeSpec[] = [
  { id: "gene-token", width: 190, height: 100 },
  { id: "filters-passed", width: 190, height: 100 },
  { id: "layer-classification", width: 320, height: 280 },
  { id: "desirability-transform", width: 280, height: 240 },
  { id: "mutation-category", width: 230, height: 150 },
  { id: "gene-role-flip", width: 230, height: 150 },
  { id: "fusion-confidence", width: 210, height: 130 },
  { id: "fusion-weight-zeroed", width: 230, height: 150 },
  { id: "d-gene", width: 190, height: 110 },
  { id: "correlation-discount", width: 260, height: 180 },
  { id: "d-combination", width: 190, height: 110 },
  { id: "veto", width: 230, height: 150 },
  { id: "partition-bucket", width: 230, height: 130 },
];

const LANE1_LAYOUT = layoutRow(LANE1_SPECS, LANE1_Y);
const LANE2_LAYOUT = layoutRow(LANE2_SPECS, LANE2_Y);

const LAST_LANE1 = LANE1_SPECS[LANE1_SPECS.length - 1].id;
const LAST_LANE2 = LANE2_SPECS[LANE2_SPECS.length - 1].id;
const VIEW_W = Math.max(
  LANE1_LAYOUT[LAST_LANE1].x + LANE1_LAYOUT[LAST_LANE1].w,
  LANE2_LAYOUT[LAST_LANE2].x + LANE2_LAYOUT[LAST_LANE2].w,
) + 24;
const VIEW_H = TIER_Y + 150;

const LAYER_ORDER: LayerName[] = ["rna", "protein", "fusion", "copy_number", "mutation", "dependency"];

// PRODUCT_SURFACE.md SS4.1 -- static pipeline facts, never read from `line`. Independent of the
// six scored layers: two of these (HPA, GEO) are corroboration-only sources, and miRNA is a
// context/filter-only layer, never scored (PLAN.md SS4).
const STATIC_TRANSFORM_FACTS = [
  "DepMap RNA (scored): log2(TPM+1)",
  "HPA RNA (corroboration only): log2(nTPM+1)",
  "GEO RNA (corroboration/breadth only): log1p(raw)",
  "miRNA (context/filter only, never scored): log1p(raw)",
  "Protein (scored): z-score (upstream) + detection-floor imputation",
  "Copy number (scored): relative to diploid (~1.0)",
  "CRISPR dependency (scored): Chronos, negated at scoring time",
];

const PARTITION_LABELS: Record<string, string> = {
  ranked: "ranked (displayed in the top-N)",
  ranked_beyond_top_n: "eligible beyond the displayed top-N",
  low_confidence: "low confidence (not a recommendation)",
  insufficient_evidence: "insufficient evidence (not ranked)",
  disqualified: "disqualified (native veto or floor rule)",
};

function classifyLayer(detail: LayerDetail): string {
  if (detail.state === "not_assayed") return "never assayed";
  if (detail.state === "non_detected") return "assayed, target not detected";
  if (detail.state === "excluded_pan_essential") return "pan-essential gate fired";
  if (detail.state === "measured_absent") return "confident negative";
  if (detail.state === "measured" && detail.gene_class === "unknown" && detail.d === null) {
    return "gene role unknown, abstained";
  }
  if (detail.state === "measured") return "measured, scored normally";
  return `unrecognized native state: ${detail.state}`;
}

function vetoReasonText(reason: string): string {
  if (reason === "exclusion_expressed") return "exclusion gene is expressed";
  if (reason === "inclusion_below_floor") return "inclusion gene is below its detection floor";
  return reason;
}

interface FlowNodeProps {
  id: string;
  layout: Record<string, { x: number; y: number; w: number; h: number }>;
  title: string;
  variant?: "default" | "not-traced" | "static-fact" | "trunk" | "annotation";
  children: ReactNode;
}

function FlowNode({ id, layout, title, variant = "default", children }: FlowNodeProps) {
  const pos = layout[id];
  if (!pos) return null;
  const classNames = ["flow-node"];
  if (variant === "not-traced") classNames.push("flow-node-not-traced");
  if (variant === "static-fact") classNames.push("flow-node-static-fact");
  if (variant === "trunk") classNames.push("flow-node-trunk");
  if (variant === "annotation") classNames.push("flow-node-annotation");
  const titlePrefix = variant === "not-traced" ? "not traced -- " : variant === "static-fact" ? "pipeline fact -- " : "";
  return (
    <foreignObject x={pos.x} y={pos.y} width={pos.w} height={pos.h}>
      <div className={classNames.join(" ")}>
        <div className="flow-node-title">
          {titlePrefix}
          {title}
        </div>
        <div className="flow-node-body">{children}</div>
      </div>
    </foreignObject>
  );
}

function centerOf(pos: { x: number; y: number; w: number; h: number }): { x: number; y: number } {
  return { x: pos.x + pos.w / 2, y: pos.y + pos.h / 2 };
}

function SequentialEdges({
  layout,
  specs,
}: {
  layout: Record<string, { x: number; y: number; w: number; h: number }>;
  specs: NodeSpec[];
}) {
  const edges: ReactNode[] = [];
  for (let i = 0; i < specs.length - 1; i += 1) {
    const from = centerOf(layout[specs[i].id]);
    const to = centerOf(layout[specs[i + 1].id]);
    edges.push(
      <line
        key={`${specs[i].id}-${specs[i + 1].id}`}
        x1={from.x}
        y1={layout[specs[i].id].y + layout[specs[i].id].h}
        x2={to.x}
        y2={layout[specs[i + 1].id].y}
        stroke="var(--border)"
        strokeWidth={2}
        opacity={0.6}
      />,
    );
  }
  return <g>{edges}</g>;
}

// V7-8: the flowchart shows one gene's path at a time -- PerGeneEvidenceTable.tsx already
// tabulates every gene x every layer's raw value/d/state elsewhere in the same detail view, so
// the flowchart's value-add is the branching path, not a second table. Trunk nodes (D, veto,
// confidence_tier, m/m_eff, partition bucket) are gene-independent and stay fixed regardless of
// which gene pill is selected.
export function ResultFlowchartDiagram({ line, partitionBucket }: ResultFlowchartDiagramProps) {
  const [selectedGeneId, setSelectedGeneId] = useState<string | null>(line.per_gene[0]?.ensembl_id ?? null);

  if (line.per_gene.length === 0) {
    return <p className="flowchart-empty">This result has no per-gene evidence to trace.</p>;
  }

  const gene: PerGeneResult =
    line.per_gene.find((g) => g.ensembl_id === selectedGeneId) ?? line.per_gene[0];

  const rho = line.rho_bar[gene.ensembl_id];
  const panEssentialWarning = line.warnings.find(
    (w) => w.type === "pan_essential" && w.ensembl_id === gene.ensembl_id,
  );
  const activeLayers = LAYER_ORDER.map((l) => [l, gene.layers[l]] as const).filter(([, d]) => d.d !== null);

  return (
    <div className="flowchart-diagram-wrap">
      <div className="flowchart-gene-selector" role="tablist" aria-label="Select a gene to trace">
        {line.per_gene.map((g) => (
          <button
            key={g.ensembl_id}
            type="button"
            role="tab"
            aria-selected={g.ensembl_id === gene.ensembl_id}
            className={g.ensembl_id === gene.ensembl_id ? "flowchart-gene-pill active" : "flowchart-gene-pill"}
            onClick={() => setSelectedGeneId(g.ensembl_id)}
          >
            {g.symbol} ({g.role})
          </button>
        ))}
      </div>

      <div className="flowchart-svg-wrap">
        <svg viewBox={`0 0 ${VIEW_W} ${VIEW_H}`} width="100%" role="img" aria-label={`Result path for ${gene.symbol}`}>
          <SequentialEdges layout={LANE1_LAYOUT} specs={LANE1_SPECS} />
          <SequentialEdges layout={LANE2_LAYOUT} specs={LANE2_SPECS} />
          <line
            x1={centerOf(LANE1_LAYOUT[LAST_LANE1]).x}
            y1={LANE1_LAYOUT[LAST_LANE1].y + LANE1_LAYOUT[LAST_LANE1].h}
            x2={centerOf(LANE2_LAYOUT["gene-token"]).x}
            y2={LANE2_LAYOUT["gene-token"].y}
            stroke="var(--accent)"
            strokeWidth={2}
            opacity={0.5}
          />
          <line
            x1={centerOf(LANE2_LAYOUT["d-combination"]).x}
            y1={LANE2_LAYOUT["d-combination"].y + LANE2_LAYOUT["d-combination"].h}
            x2={centerOf(LANE2_LAYOUT["d-combination"]).x + 60}
            y2={TIER_Y}
            stroke="var(--border)"
            strokeWidth={2}
            strokeDasharray="4,3"
            opacity={0.8}
          />

          {/* Lane 1 -- preprocessing */}
          <FlowNode id="spine" layout={LANE1_LAYOUT} title="On the identity spine">
            <p>This cell line appears in the result at all -- it resolved to a ModelID on the identity spine.</p>
          </FlowNode>
          <FlowNode id="identity-bridge" layout={LANE1_LAYOUT} title="Identity bridge" variant="not-traced">
            <p>Which bridge (HPA name, GEO GSM, CCLE, direct, or Model.csv backfill) resolved this ModelID is a build-level fact with no per-line field.</p>
          </FlowNode>
          <FlowNode id="dup-rna" layout={LANE1_LAYOUT} title="Duplicate RNA profiles averaged" variant="not-traced">
            <p>Whether this line's RNA profiles were among the 16 repo-wide duplicates averaged during preprocessing has no per-line flag.</p>
          </FlowNode>
          <FlowNode id="layer-states" layout={LANE1_LAYOUT} title={`Per-layer assay state -- ${gene.symbol}`}>
            <ul className="flow-node-list">
              {LAYER_ORDER.map((l) => {
                const detail = gene.layers[l];
                return (
                  <li key={l}>
                    <strong>{l}:</strong> {stateLabel(detail.state)}
                    {detail.value === null ? "" : ` -- ${detail.value} ${detail.unit}`}
                  </li>
                );
              })}
            </ul>
          </FlowNode>
          <FlowNode
            id="protein-impute"
            layout={LANE1_LAYOUT}
            title="Protein detection-floor imputation"
            variant={gene.layers.protein.state === "non_detected" ? "default" : "annotation"}
          >
            {gene.layers.protein.state === "non_detected" ? (
              <p>Reached: protein was not detected. The imputed detection floor exists in protein.csv for provenance but is never surfaced as this gene's value (value is null here).</p>
            ) : (
              <p>Not reached for this gene -- protein state is {stateLabel(gene.layers.protein.state)}.</p>
            )}
          </FlowNode>
          <FlowNode id="transforms" layout={LANE1_LAYOUT} title="Per-layer transform applied" variant="static-fact">
            <ul className="flow-node-list">
              {STATIC_TRANSFORM_FACTS.map((fact) => (
                <li key={fact}>{fact}</li>
              ))}
            </ul>
          </FlowNode>
          <FlowNode id="coverage-states" layout={LANE1_LAYOUT} title="Three-state vs two-state coverage">
            <p>Only mutations_state and fusions_state are genuinely three-state in coverage.csv. The other seven layers are two-state -- measured_absent is resolved per (line, gene) at scoring time, not a coverage.csv column.</p>
          </FlowNode>

          {/* Lane 2 -- scoring */}
          <FlowNode id="gene-token" layout={LANE2_LAYOUT} title="Gene token resolved">
            <p>{gene.symbol} ({gene.ensembl_id}) resolved as a query {gene.role} gene.</p>
          </FlowNode>
          <FlowNode id="filters-passed" layout={LANE2_LAYOUT} title="Candidate passed the filters">
            <p>Implicit -- this line is in the response, so it passed every query filter that was applied.</p>
          </FlowNode>
          <FlowNode id="layer-classification" layout={LANE2_LAYOUT} title="Layer abstention / classification">
            <ul className="flow-node-list">
              {LAYER_ORDER.map((l) => {
                const detail = gene.layers[l];
                return (
                  <li key={l}>
                    <strong>{l}:</strong> {classifyLayer(detail)}
                  </li>
                );
              })}
            </ul>
            {panEssentialWarning && <p className="flow-node-corroboration">{panEssentialWarning.message}</p>}
          </FlowNode>
          <FlowNode id="desirability-transform" layout={LANE2_LAYOUT} title="Desirability transform (value -> d)">
            {activeLayers.length === 0 ? (
              <p>No layer produced a d for this gene -- every layer abstained.</p>
            ) : (
              <ul className="flow-node-list">
                {activeLayers.map(([l, detail]) => (
                  <li key={l}>
                    {l}: {detail.value} {detail.unit} {"->"} d = {formatScore(detail.d)}
                  </li>
                ))}
              </ul>
            )}
          </FlowNode>
          <FlowNode id="mutation-category" layout={LANE2_LAYOUT} title="Mutation category ladder">
            <p>
              Category: <strong>{String(gene.layers.mutation.value ?? "n/a")}</strong>
              <br />
              state: {gene.layers.mutation.state}, d = {formatScore(gene.layers.mutation.d)}, gene_class:{" "}
              {gene.layers.mutation.gene_class ?? "unknown"}
            </p>
          </FlowNode>
          <FlowNode id="gene-role-flip" layout={LANE2_LAYOUT} title="Gene-role direction flip">
            <p>
              mutation gene_class: <strong>{gene.layers.mutation.gene_class ?? "unknown"}</strong>
              <br />
              copy_number gene_class: <strong>{gene.layers.copy_number.gene_class ?? "unknown"}</strong>
              <br />
              {(gene.layers.mutation.gene_class ?? "unknown") === "unknown" &&
                (gene.layers.copy_number.gene_class ?? "unknown") === "unknown" &&
                "Unknown gene role abstains on both layers rather than guessing a direction."}
            </p>
          </FlowNode>
          <FlowNode id="fusion-confidence" layout={LANE2_LAYOUT} title="Fusion confidence modifier">
            <p>
              confidence_factor = {gene.layers.fusion.confidence_factor ?? "n/a"}
              <br />
              Only scales the fusion layer's weight when state is "measured" (a real fusion event read).
            </p>
          </FlowNode>
          <FlowNode
            id="fusion-weight-zeroed"
            layout={LANE2_LAYOUT}
            title="Fusion weight zeroed (U3)"
            variant={gene.fusion_weight_zeroed ? "default" : "annotation"}
          >
            {gene.fusion_weight_zeroed ? (
              <p>True -- this exclusion gene's assayed_no_fusion (measured_absent) fusion reading was dropped to weight 0 in d_gene's weighted mean, so it stops diluting the other layers' evidence. d itself is unchanged.</p>
            ) : (
              <p>False -- not applicable ({gene.role} role, or fusion state is not the exclusion-role measured_absent case this branch targets).</p>
            )}
          </FlowNode>
          <FlowNode id="d-gene" layout={LANE2_LAYOUT} title="Within-gene combination">
            <p>d_gene = {formatScore(gene.d_gene)}</p>
            <p className="flow-node-note">Null when every layer abstained -- never a scored zero.</p>
          </FlowNode>
          <FlowNode id="correlation-discount" layout={LANE2_LAYOUT} title="Correlation discount">
            <p>
              m_eff = {formatScore(line.m_eff)} of {line.m} scored gene(s)
              <br />
              rho_bar[{gene.symbol}] = {rho === null || rho === undefined ? "n/a" : formatScore(rho)}
            </p>
            {line.m === 1 && <p className="flow-node-note">m = 1 -- no correlation discount applied (short-circuit).</p>}
          </FlowNode>
          <FlowNode id="d-combination" layout={LANE2_LAYOUT} title="Across-gene combination" variant="trunk">
            <p>D = {formatScore(line.D)}</p>
          </FlowNode>
          <FlowNode id="veto" layout={LANE2_LAYOUT} title="Veto fired?" variant="trunk">
            {line.veto ? (
              <p>
                Vetoed by <strong>{line.veto.symbol}</strong> ({vetoReasonText(line.veto.reason)}).
              </p>
            ) : (
              <p>No veto triggered.</p>
            )}
          </FlowNode>
          <FlowNode id="partition-bucket" layout={LANE2_LAYOUT} title="Partition bucket" variant="trunk">
            <p>{PARTITION_LABELS[partitionBucket] ?? partitionBucket}</p>
          </FlowNode>

          <FlowNode
            id="confidence-tier"
            layout={{ "confidence-tier": { x: centerOf(LANE2_LAYOUT["d-combination"]).x + 60, y: TIER_Y, w: 260, h: 110 } }}
            title="Confidence tier (side annotation)"
            variant="annotation"
          >
            <p>
              {line.confidence_tier} -- reported beside D, never multiplied into it. Not part of the D calculation.
            </p>
          </FlowNode>
        </svg>
      </div>
    </div>
  );
}
